### ISSUE TITLE
python with

### ISSUE THREAD

**Issue by jack-ew** [craftyguy/autolight#3]
Hi,
to read the sensor, you can use:
```python
with open(dev, 'r') as f:
    illum = int(f.read())
```
instead of:
```python
f = open(dev, 'r')
illum = int(f.read())
f.close()
```
the with-statement close 'f' automatically, even in the case of an error.

**Comment by craftyguy** [comment]
Awesome, thank you for the help! I'll fix that.

**Comment by craftyguy** [comment]
Fixed! Thanks again :)
